version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
